/**
 * The baked ambient-blob textures. GENERATED by scripts/make-blobs.py — do not edit.
 *
 * Metro resolves `require` at build time, so the paths have to be literal and the ladder has to be
 * mirrored here. Both are written out by the generator rather than kept in step by hand: the
 * overscan figures in particular are geometry the generator knows and a reader would only be
 * guessing at.
 */

export const BLOB_RATIOS = [0.113, 0.132, 0.151, 0.176, 0.203, 0.232] as const;

/**
 * How much larger each texture is than the disc inside it.
 *
 * In the design the gradient fills the element and its blur spills outside, so the texture is drawn
 * oversized and centred on the layout box; the disc inside it then lands at exactly `size`.
 */
export const BLOB_OVERSCAN = [1.4609, 1.5391, 1.6172, 1.7188, 1.8203, 1.9375] as const;

export type BlobRing = 'cool' | 'warm' | 'dusk' | 'teal';

const TEXTURES: Record<BlobRing, number[]> = {
  cool: [
    require('../../assets/blobs/cool-0.png'),
    require('../../assets/blobs/cool-1.png'),
    require('../../assets/blobs/cool-2.png'),
    require('../../assets/blobs/cool-3.png'),
    require('../../assets/blobs/cool-4.png'),
    require('../../assets/blobs/cool-5.png'),
  ],
  warm: [
    require('../../assets/blobs/warm-0.png'),
    require('../../assets/blobs/warm-1.png'),
    require('../../assets/blobs/warm-2.png'),
    require('../../assets/blobs/warm-3.png'),
    require('../../assets/blobs/warm-4.png'),
    require('../../assets/blobs/warm-5.png'),
  ],
  dusk: [
    require('../../assets/blobs/dusk-0.png'),
    require('../../assets/blobs/dusk-1.png'),
    require('../../assets/blobs/dusk-2.png'),
    require('../../assets/blobs/dusk-3.png'),
    require('../../assets/blobs/dusk-4.png'),
    require('../../assets/blobs/dusk-5.png'),
  ],
  teal: [
    require('../../assets/blobs/teal-0.png'),
    require('../../assets/blobs/teal-1.png'),
    require('../../assets/blobs/teal-2.png'),
    require('../../assets/blobs/teal-3.png'),
    require('../../assets/blobs/teal-4.png'),
    require('../../assets/blobs/teal-5.png'),
  ],
};

/** The rung whose blur ratio is closest to what the call site asked for. */
export function blobRungFor(size: number, blurPx: number): number {
  const wanted = blurPx / Math.max(1, size);
  let best = 0;
  for (let i = 1; i < BLOB_RATIOS.length; i++) {
    if (Math.abs(BLOB_RATIOS[i] - wanted) < Math.abs(BLOB_RATIOS[best] - wanted)) best = i;
  }
  return best;
}

export function blobTextureFor(ring: BlobRing, rung: number): number {
  return TEXTURES[ring][rung];
}
